# Generated by Django 3.1.3 on 2021-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_info',
            field=models.DateField(auto_now_add=True),
        ),
    ]
